### ISSUE TITLE
Mouse speed too fast in certain directions, since upgrading to macOS Sierra

### ISSUE THREAD

**Issue by nicknlsn** [symless/synergy-core#5607]
### Operating Systems

Client: Arch Linux x86_64 4.6.3-1-ARCH

Server: macOS Sierra
### Synergy Version

client: synergyc 1.8.2, protocol version 1.6
server: 1.8.2-stable-145e779
### Steps to reproduce bug

Mouse speed on server is normal, however, mouse speed on client is a little fast when moving in left or up directions, slow when moving in right or down directions. server screen is on right, client on left. It does it all the time. It seems like movement up or left is twice as sensitive as right or down.
### Other info
- When did the problem start to occur? When I did a full system upgrade on Arch for the first time in a few months.
- Is there a way to work around it? Not that I am aware of.
- Does this bug prevent you from using Synergy entirely? It is annoying but I can still use it. A lot of my interaction with my Arch Linux system is through the terminal from my Mac, so I am dealing with it. But I would like to know how to fix it. 

If you can point me in the right direction I can mess with the code myself.

**Comment by nlyan** [comment]
Hi Nick,

Thanks for following the issue template, it's a big help.  This is a dupe of bug #5183, so I'm going to have to close it. However, since you seem kean to look at the code, I would like to point you toward pull request #5190 which may be a help.

Also, my suspicion is your problem may be the upgradeto Sierra on your server and not the upgrade of Arch. Although, if I'm wrong it'd be handy to know what version you were using before on Arch (have a look at /var/log/pacman.log for synergy)

**Comment by nicknlsn** [comment]
[2016-09-21 15:49] [ALPM] upgraded synergy (1.7.6-2 -> 1.8.2-1)

I haven't changed any display settings on either machine recently. However, the upgrade to Sierra is doing something weird with one of my monitors. I have it in portrait mode and now it will not use the full native resolution for that monitor. If I switch it back to landscape it uses the full resolution. When I option+click the scaled button in the displays preferences window it lists a bunch of other resolution options, but not the full resolution of the screen. I wonder if this problem is related to the one with synergy.

The upgrade to Sierra also switched the screen that the menu bar was on. I needed to drag the menu bar back to the other screen in the display preferences. Not sure if that helps at all.

What else can I do to get you more information?

**Comment by Cheesebaron** [comment]
I have similar symptoms on a similar setup, although client is Windows instead of Linux.

**Comment by nicknlsn** [comment]
I figured out how to restore the native resolution for the portrait monitor. A user on macrumors.com posted this command: sudo defaults write /Library/Preferences/com.apple.windowserver.plist DisplayResolutionEnabled -bool true Run that and then reboot, the option for full resolution is now now. I haven't figured out how to make it permanent though, so I have to do it every once in awhile.

**Comment by chow11** [comment]
I have this problem with Windows 7 client and MacOS Sierra server.  I believe the problem started after upgrading to Sierra, but I am not 100% positive.  On my Windows laptop, suddently the external monitor was not showing the right display (I just went to sleep and in the morning the resolution was magically now smaller - I assume from a Windows update, fixed by configuring a custom screen resolution).  If I just move the cursor on the client in a circle for several seconds, I notice, that for a few seconds the mouse is jittery, then for a few seconds the mouse is fine, and back and forth...

**Comment by XinyuHou** [comment]
@nicknlsn @Cheesebaron @chow11 
Could you test our latest 10.12 build on your sierra to see if the problem persists? Thanks.
http://symless.com/nightly?filter=synergy-v1.8.6-rc1-7ce6905

**Comment by nicknlsn** [comment]
How should I compile the source for the linux system? Could you help me with a PKGBUILD for paceman? If I download the source and compile it throws a github error 128. If I put a .git folder in there it compiles but this issue persists. So I'm not sure if that means the issue still persists, or I haven't compiled the code correctly. 

I also tried reinstalling the latest with yaourt, but still saw the issue. I also cloned the current repo and compiled but still saw the issue.

**Comment by Cheesebaron** [comment]
@XinyuHou Seems to be a lot better now.

**Comment by Cheesebaron** [comment]
It is still not entirely fixed. Sometimes when moving the mouse fast around the screen it suddenly makes very long jumps. However, it is much more usable now than it was before, much more predicable.

**Comment by emiliobool** [comment]
Having same issue on sierra as server

doing short movements back and forth end up moving up and left faster

I was on 1.8.6-stable, just tried updating both client and server to 1.8.7-rc1 

still having the same issue

my client has "el capitan" and 2 QHD vertical monitors
server has "sierra" and 2x4k monitors at native resolution (no HiDPi scaling)

willing to help as well

**Comment by emiliobool** [comment]
I also tried to update to the newest nightly build I could find for sierra and it made no difference

trying to adjust my mouse acceleration I installed this app:

http://www.usboverdrive.com/USBOverdrive/News.html

and funny enough it fixed the issue, no idea why or how but maybe someone else can benefit from this find

**Comment by nicknlsn** [comment]
Hey thanks for that link! This solved the problem for me too. I guess its just a workaround, but its nice to have it working right!

**Comment by tabchas** [comment]
@emiliobool Wow that does (strangely) fix my issue!

I'm on macOS Sierra server and Windows 10 client, both running 1.8.5 stable. Once I installed and reduced the acceleration using USBOverdrive, the mouse seems to stop acting weird and is moving in expected path.

**Comment by Cheesebaron** [comment]
USBoverdrive doesn't work correctly for me. On my Windows PC when the mouse is on my screen in portrait mode it still has some kind of acceleration. On the landscape mode screen it works as expected.

**Comment by kdaker-mfour** [comment]
happening to me as well. Mouse is fast moving up and left on the client with a macOS server. 

Using MacOS Sierra on 15 macbook pro (touch bar) with a linux client. Both client and server use 1080p monitors.

**Comment by glyph** [comment]
I have 2 macs. Upgraded the client to sierra some time back, no issues.  Just upgraded the server to sierra tonight, and immediately started seeing the behavior @kdaker-mfour describes - movement up and left is 2x as fast as movement down or right.

**Comment by prodo123** [comment]
I've tried messing with the macOS mouse acceleration settings with
`defaults write .GlobalPreferences com.apple.mouse.scaling -1`
as well as the acceleration option on my mouse (via Logitech Gaming Center). The up-left bias remains regardless of the mouse settings.

**Comment by artz** [comment]
Just confirming I also have this issue, Mac OS Sierra and Windows 10 server.  Moving cursor left and top are about 2x as fast as opposite direction.

**Comment by IMcD23** [comment]
I also am having this issue. Running macOS Sierra 10.12.4 as a server and Windows 10 as a client. I don't have this issue with other software KVMs, only Synergy.

**Comment by iaian7** [comment]
I'm also seeing this issue. Mouse movement is accelerated when moving up or left. Server is a 2015 27" Retina iMac running MacOS Sierra 10.12.3 (brand new installation as of today), client is a 2011 27" non-retina iMac running OS X 10.11.6 (not so brand new installation, haha). I've tried it both with and without BetterTouchTool running both on the server side and the client side, along with changes to the mouse speed on the server. No change. Making small circles with the mouse causes it to consistently move up and to the left.

This bug effectively renders Synergy unusable.

**Comment by adamr4d** [comment]
Being as I just bought this, I'd hope something like this wouldn't be occurring. Makes using between OSX and Windows unusable.

**Comment by aminor00** [comment]
This issue has also been reported in #5291

**Comment by hectorC** [comment]
I'm experiencing the same problem, mouse speed is different in different axis. Mac OS Sierra server and Windows 10 client,  Synergy 1.8.7

**Comment by aminor00** [comment]
This appears to be the same problem as listed in this incident: #5648

**Comment by benknight04861** [comment]
YAY!!!  Thank you for finally providing a solution that actually works without having to install some extra software.  :- )

**Comment by iammoen** [comment]
The dmg that aminor00 posted fixed it for me as well. Woot!

**Comment by jwm63** [comment]
Is there any status on the original issue this topic was opened for?  Mouse speed too fast on clients with Mac OS X Sierra server and linux clients.  I'd like to get back to using my Mac as my Synergy server.

**Comment by deckar01** [comment]
I update from MacOS 10.12.0 to 10.12.5 and started experiencing this behavior. I am using Synergy 1.8.8 on a OpenSUSE Tumbleweed client and a MacOS 10.12 server.

If I move my cursor too slowly in certain directions, the movement only registers on one axis. Here are some example velocity vectors I am seeing:

> _Note: Vectors are using the cartesian coordinate system <V<sub>x</sub> , V<sub>y</sub>> and the values are estimated pixels per update cycle._

| Server | Client |
|---|---|
| <1, 1> | <1, 1> |
| <0.5, 0.5> | <**0**, 0.5> |
| <-1, -1> | <-1, -1> |
| <-0.5, -0.5> | <-0.5, **0**> |
| <0.5, -0.5> | <0.5, -0.5> |
| <-0.5, 0.5> | <-0.5, 0.5> |

 - Moving slowly up and to the right **looses horizontal movement**
 - Moving slowly down and to left **loses vertical movement**
 - Moving slowly up and to the left behaves as expected
 - Moving slowly down and to the right behaves as expected

**Comment by aminor00** [comment]
Have you tried the special build version that PutzWorks created and I linked to in the comments above?

You only need the server side to be updated on MacOS Sierra to fix it (with a Windows 7 and 10 client).  On a Linux client YMMV but it's worth a shot as I believe the issue is on the server side not the client.

**Comment by deckar01** [comment]
I just installed that build on my server. My cursor is now smoother than it has ever been (even before this bug). Thank you!

**Comment by jwm63** [comment]
per the above comment from aminor00, I pulled down the version from PutzWorks.  Server is OSX Sierra 10.12.5.  Clients are RHEL 7.3 and Fedora 25 both running version 1.8.8-1, which appears to be the latest available from the download site.

Cursor speed on the 2 clients is a bit more useable, but still somewhat erratic.

And... a wild thought came to me...  since deckar01 reported success and mine was only a little better and still seemed to "jump" frequently. I always use my trackpads (internal, and the newer Apple bluetooth one)... could there be a difference with a "mouse"?  So I connected the closest thing I have... a Logitech Cordless Optical TrackMan trackball to the Mac/server and it displayed exceptionally better speed control than the trackpads.  For the developers/programmers... are there acceleration differences between mouse/trackball and trackpads?

**Comment by jwm63** [comment]
I'm totally baffled now!!!  
I've been using the the trackpad on the Mac/server all day when working on the Mac, then switching to the trackball when needing to do stuff on either client.  I (just now, after 8 hours of work) slipped into old habits and accidentally used the trackpad to navigate to the clients and it's behaving PERFECTLY!  No jumping/skipping/erratic movements.  No reboots of the server or either client. Nothing I can think I did differently.  Over the weekend I'll reboot each of the 3 systems and see if everything stays good or if it relapses.  For the moment, at least, I'm ecstatic!

**Comment by jwm63** [comment]
I've rebooted all systems and the cursor seemed to be somewhat erratic, then settled down later without any further action taken.

**Comment by Cheesebaron** [comment]
Almost a year now and this issue still hasn't been fixed in a stable released version of Synergy? Would be great to get a release soon with the fixes in 😄

**Comment by jwm63** [comment]
I agree with Cheesebaron.  My problem came back again.  No rhyme or reason to when it works good or goes spastic/erratic on me.  I'm down to only 2 systems right now, so I've stopped using it and just swivel between my bluetooth keyboard & touchpad for the Macbook and a Thinkpad Traveler keyboard/touchpad for the linux system. I'm glad the purchase was one-time.

**Comment by artz** [comment]
Yeah, agreed. Is this project still active?  OS X Sierra has been out for nearly a year.

**Comment by deckar01** [comment]
@artz It looks like they are gearing up for a v2 release that requires a new paid license for existing customers.

https://github.com/symless/synergy-core/issues/6155

**Comment by jakemauer** [comment]
Because of a repo name change the URL to the special build that fixes this issue will 404. Here's the corrected URL: https://github.com/symless/synergy-core/files/902511/synergy-v1.8.8-pr-5648-stable-1c1067d-MacOSX-x86_64.dmg.zip

**Comment by jwm63** [comment]
I had that same version previously installed before I tried V2.  Have problems with V2 on the Mac I've emailed Sarah on.  I've fallen the Mac back to this version of 1.8.8-pr-5648 (removed my prior copy and downloaded again) and will test it again for a few days.

**Comment by jwm63** [comment]
I just had a repeat of the mouse going erratic on linux.  Mac is server, linux is client.  V1.8.8 on both.  Will attempt to reproduce, but it seemed to trigger after I tried using the native mouse on the linux system.  Killed the client and restart didn't help, erratic behavior continued. Upgraded linux client to V2 (mac still at 1.8.8) and it's stable again.

**Comment by jwm63** [comment]
duplicated,  mouse goes erratic after trying to use native mouse on linux. V1.8.8 on Mac (server), V2 on linux.  Killing and restarting synergyc on linux doesn't resolve the issue immediately... tho mouse sat quiet while I typed this on the linux system and it grew stable again.

**Comment by nbolton** [comment]
Duplicates: https://github.com/symless/synergy-core/issues/5648

**Comment by kitizz** [comment]
This bug (and #5648) are back in Synergy 2.0.4

Version 2 really feels like it should be carrying a Beta suffix right now. The automatic improvements for networking are fantastic and good to see. But I paid for this upgrade based on promises of it being the latest and greatest -- I don't expect regressions like this.

If this were open source or free software, or v2 had a beta tag, I would have a lot more patience around this issue.

(But seriously, keep up the overall good work. Synergy is still the best at what it does! I'm keen to see it stay that way)
